// BOOKS ---------------------------------------
const SELECT_ALL_BOOKS = "SELECT_ALL_BOOKS";
const SELECT_BOOK_BY_ID = "SELECT_BOOK_BY_ID";
const UPDATE_BOOK = "UPDATE_BOOK";
const DELETE_BOOK = "DELETE_BOOK";
const INSERT_BOOK = "INSERT_BOOK";
const EXIST_BOOK = "EXIST_BOOK";
const EXIST_ISBN = "EXIST_ISBN";
const EXIST_ISBN_PUT = "EXIST_ISBN_PUT";

// AUTHOR ---------------------------------------
const SELECT_ALL_AUTHORS = "SELECT_ALL_AUTHORS";
const SELECT_AUTHOR_BY_ID = "SELECT_AUTHOR_BY_ID";
const UPDATE_AUTHOR = "UPDATE_AUTHOR";
const DELETE_AUTHOR = "DELETE_AUTHOR";
const INSERT_AUTHOR = "INSERT_AUTHOR";
const EXIST_AUTHOR = "EXIST_AUTHOR";


module.exports = {
    SELECT_ALL_AUTHORS,
    SELECT_AUTHOR_BY_ID,
    UPDATE_AUTHOR,
    DELETE_AUTHOR,
    INSERT_AUTHOR,
    EXIST_AUTHOR,
    SELECT_ALL_BOOKS,
    SELECT_BOOK_BY_ID,
    UPDATE_BOOK,
    DELETE_BOOK,
    INSERT_BOOK,
    EXIST_BOOK,
    EXIST_ISBN,
    EXIST_ISBN_PUT
}